title: Concentradora de Información Jurídica
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.8914894
  rhythmicContrast: 0
  brandColors:
    - '#FFFFFB'
    - '#0F1014'
    - '#0053A3'
    - '#C9C0B7'
    - '#6C6E63'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Soporte Legal
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3106383
layout_spectrum: 0.5638298
