name: Soporte Legal
favicon: null
layout_spectrum: 0.5152171475347131
typography_spectrum: 0.3765157728921622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.62822415237315
  lightness: 0.9030578343663365
  saturation: 0.085968705592677
  rhythmicContrast: 0.25180621654726565
purpose: []
